### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by AlecRubin** [hyperoslo/facebook-messenger#9] opened 2016-04-29 16:16 UTC
I was able to get through about 90% of the installation process. Facebook accepted the webhook, but when I go to message my bot, I don't get a response, so I looked at the logs on my server and I'm getting this.

NoMethodError (undefined method `fetch' for nil:NilClass):

Any clue what's wrong?

**Comment by frodsan** [comment] 2016-04-29 17:28
Can you create a script that reproduces this issue?

**Comment by frodsan** [comment] 2016-04-29 17:37
I think it's because of this line:

https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/bot.rb#L63

If there are no hooks registered, @hooks will be nil.

**Comment by frodsan** [comment] 2016-04-29 17:43
Here is an example:

```
require "bundler/setup"
require_relative "lib/facebook/messenger"

Facebook::Messenger::Bot.trigger(:message, 'o')
facebook-messenger/lib/facebook/messenger/bot.rb:63:in `trigger': undefined method `fetch' for nil:NilClass (NoMethodError)
```

**Comment by frodsan** [comment] 2016-04-29 17:48
After #10, the result is:

```ruby
require "bundler/setup"
require_relative "lib/facebook/messenger"

Facebook::Messenger::Bot.trigger(:message, 'o')
# => Ignoring message (no hook registered)
```

**Comment by AlecRubin** [comment] 2016-04-29 19:00
How do you register a hook?

**Comment by jgorset** [comment] 2016-04-29 19:05
That seems a likely culprit, @frodsan. If you give us the full stack trace we'll know for sure, though, @AlecRubin.

**Comment by jgorset** [comment] 2016-04-29 19:05
When @frodsan refers to hook, he means `Bot.on :something`. We call those somethings hooks internally.

**Comment by frodsan** [comment] 2016-04-29 19:30
Can you try your script with 0.4.0? https://rubygems.org/gems/facebook-messenger/versions/0.4.0

**Comment by jgorset** [comment] 2016-05-03 18:08
I'm gonna close this pending a reply from @AlecRubin.

**Closed by jgorset** 2016-05-03 18:08 UTC
