### ISSUE TITLE
Facebook::Messenger::Welcome.set broken by Facebook API change

### ISSUE THREAD

**Issue by daniel-sim** [hyperoslo/facebook-messenger#50] opened 2016-07-01 14:58 UTC
This bug:
https://developers.facebook.com/bugs/1751749508372552/

Has broken Facebook::Messenger::Welcome.set as the API call now only supports one call_to_action with a payload string:

https://developers.facebook.com/docs/messenger-platform/thread-settings/get-started-button

Fixed locally by changing ```welcome_setting_for``` to ```call_to_actions: payload ? [payload] : []``` allowing us to call ```Facebook::Messenger::Welcome.set payload: "HELLO"``` without error.

**Comment by sorich87** [comment] 2016-07-02 03:33
More information: it's not a bug that Facebook will fix. It's a breaking change. https://developers.facebook.com/docs/messenger-platform/changelog#20160630

**Comment by jgorset** [comment] 2016-07-02 10:56
Fixed in #51. Thanks guys!

**Closed by jgorset** 2016-07-02 10:56 UTC
